### ISSUE TITLE
Central Yharnam & Cathedral Ward (blood moon)

### ISSUE THREAD

**Issue by Kerkerseele** [modo-lv/bloodborne-checklist#3]
I hope I'm not too late. I love this checklist and hope it stays forever (I used it for over 8 playthroughs so far.) A certain step is missing for the White Messenger Ribbon.
If you've killed the Goliath Pig in the sewers to get Red Messenger Ribbon, you can return to Viola's window during the Blood Moon to talk to the older sister and turn in the Red Messenger Ribbon. Reload the area and go down the ladder for the White Messenger Ribbon.

**Comment by Kerkerseele** [comment]
Another one for Fishing Hamlet (DLC):
Right before Orphan - Pick up Blood Rock.

**Comment by Kerkerseele** [comment]
Research Hall is "DONE" (12/12) before defeating Failures and Maria. Should start at 0/14.

**Comment by thulin82** [comment]
Added PR #4 to fix all three issues

FYI, for the future, write ONE issue for ONE problem, so that individual issues can be solved and closed 😄 

FY2: I have to play Bloodborne again... 😆

**Comment by thulin82** [comment]
Ping @Kerkerseele & @modo-lv

**Comment by modo-lv** [comment]
Thanks, merged.
